const DB='financeDB', VER=1; let db, state={income:[],expense:[],dues:[]}, deferredPrompt=null;
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{let d=r.result;['income','expense','dues'].forEach(x=>{if(!d.objectStoreNames.contains(x))d.createObjectStore(x,{keyPath:'id',autoIncrement:true})})};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function all(store){return new Promise((res,rej)=>{let r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(store,obj){return new Promise((res,rej)=>{let r=db.transaction(store,'readwrite').objectStore(store).add(obj);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function del(store,id){db.transaction(store,'readwrite').objectStore(store).delete(id);setTimeout(refresh,50)}
async function refresh(){for(let k of Object.keys(state))state[k]=await all(k);render()}
function val(id){return document.getElementById(id).value}
async function addIncome(){let amount=+val('iAmount');if(!amount)return alert('Enter amount');await put('income',{date:val('iDate')||today(),amount,source:val('iSource'),note:val('iNote')});['iAmount','iSource','iNote'].forEach(x=>document.getElementById(x).value='');refresh()}
async function addExpense(){let amount=+val('eAmount');if(!amount)return alert('Enter amount');await put('expense',{date:val('eDate')||today(),amount,cat:val('eCat'),method:val('eMethod'),note:val('eNote')});['eAmount','eMethod','eNote'].forEach(x=>document.getElementById(x).value='');refresh()}
async function addDue(){let name=val('dueName'),amount=+val('dueAmount'),day=+val('dueDay');if(!name||!amount||!day)return alert('Enter due name, amount and day');await put('dues',{name,amount,day,paid:false});['dueName','dueAmount','dueDay'].forEach(x=>document.getElementById(x).value='');refresh()}
function today(){return new Date().toISOString().slice(0,10)}
function render(){let inc=state.income.reduce((a,x)=>a+x.amount,0),exp=state.expense.reduce((a,x)=>a+x.amount,0);dIncome.textContent=money(inc);dExpense.textContent=money(exp);dBalance.textContent=money(inc-exp);
incomeList.innerHTML=state.income.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="row"><span>${esc(x.date)}</span><b class="income">${money(x.amount)}</b><span>${esc(x.source)}</span><span>${esc(x.note)}</span><span class="actions"><button class="btn danger" onclick="del('income',${x.id})">Delete</button></span></div>`).join('')||'<p class="muted">No income records.</p>';
expenseList.innerHTML=state.expense.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="row"><span>${esc(x.date)}</span><b class="expense">${money(x.amount)}</b><span>${esc(x.cat)}</span><span>${esc(x.note)} ${x.method?'('+esc(x.method)+')':''}</span><span class="actions"><button class="btn danger" onclick="del('expense',${x.id})">Delete</button></span></div>`).join('')||'<p class="muted">No expense records.</p>';
dueList.innerHTML=state.dues.map(x=>`<div class="due"><b>${esc(x.name)}</b><span>${money(x.amount)}</span><span>Every month: ${x.day}</span><span class="pill ${x.paid?'paid':''}">${x.paid?'Paid':'Pending'}</span><span class="actions"><button class="btn" onclick="toggleDue(${x.id},${!x.paid})">${x.paid?'Mark Pending':'Mark Paid'}</button><button class="btn danger" onclick="del('dues',${x.id})">Delete</button></span></div>`).join('')||'<p class="muted">No monthly dues.</p>';
dashDues.innerHTML=state.dues.filter(x=>!x.paid).map(x=>`<div class="row"><b>${esc(x.name)}</b><span>${money(x.amount)}</span><span>Due day ${x.day}</span><span class="pill">Pending</span></div>`).join('')||'<p class="muted">No pending dues.</p>'; report()}
async function toggleDue(id,paid){let x=state.dues.find(x=>x.id===id);x.paid=paid;db.transaction('dues','readwrite').objectStore('dues').put(x);setTimeout(refresh,50)}
function show(id,btn){document.querySelectorAll('main>section').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');if(id==='reports')report()}
function report(){let m=val('month')||today().slice(0,7),inc=state.income.filter(x=>x.date.startsWith(m)).reduce((a,x)=>a+x.amount,0),exp=state.expense.filter(x=>x.date.startsWith(m)).reduce((a,x)=>a+x.amount,0);reportBox.innerHTML=`<div><small>Income</small><br><b class="income">${money(inc)}</b></div><div><small>Expense</small><br><b class="expense">${money(exp)}</b></div><div><small>Balance</small><br><b class="balance">${money(inc-exp)}</b></div>`;let cats={};state.expense.filter(x=>x.date.startsWith(m)).forEach(x=>cats[x.cat]=(cats[x.cat]||0)+x.amount);catBox.innerHTML='<h3>Expense by Category</h3>'+Object.entries(cats).map(([k,v])=>`<div class="row"><b>${esc(k)}</b><span>${money(v)}</span></div>`).join('')||'<p class="muted">No expenses for this month.</p>'}
async function exportData(){let out=JSON.stringify(state,null,2),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([out],{type:'application/json'}));a.download='finance-backup-'+today()+'.json';a.click()}
async function importData(e){let f=e.target.files[0];if(!f)return;let data=JSON.parse(await f.text());if(!data.income||!data.expense||!data.dues)return alert('Invalid backup');await clearStores();for(let k of Object.keys(state))for(let x of data[k]){let y={...x};delete y.id;await put(k,y)}refresh();alert('Backup restored')}
function clearStores(){return Promise.all(Object.keys(state).map(k=>new Promise(r=>{let q=db.transaction(k,'readwrite').objectStore(k).clear();q.onsuccess=()=>r()})))}
async function clearAll(){if(confirm('Delete all finance data from this device?')){await clearStores();refresh()}}
let installEvent; window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e});async function installApp(){if(installEvent){installEvent.prompt();installEvent=null}else alert('On Chrome Android, use the browser menu → Add to Home screen.')}
(async()=>{await openDB();iDate.value=today();eDate.value=today();month.value=today().slice(0,7);await refresh();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js')})()
